### ISSUE TITLE
import not found: differenceWith

### ISSUE THREAD

**Issue by mcl-sz** [dannyYassine/vuuri#12]
Hi @dannyYassine,

Thanks for making Vuuri available! I am experiencing the following console error: import not found: differenceWith.
This occurs in Vuuri.vue line 25
https://github.com/dannyYassine/vuuri/blob/91f22c1798e50789822d039dfd5ba5333ba42377/src/Vuuri.vue#L25

Does an additional dependency need to be installed?

**Comment by dannyYassine** [comment]
hi @mcl-sz , thanks for letting me know!

This PR: https://github.com/dannyYassine/vuuri/pull/13/files should fix it.

It should be merged sometime today.

Many thanks.

**Comment by dannyyassine-ce** [comment]
@mcl-sz you can try again.

Many thanks.

**Comment by dannyYassine** [comment]
@mcl-sz you can try again.

Many thanks.
