### ISSUE TITLE
I think this is a dangling console.log

### ISSUE THREAD

**Issue by codeallthethingz** [dannyYassine/vuuri#15]
I love working with Vuuri so far! 
 <3 

I'm getting a bunch of log statements in my app

<img width="552" alt="image" src="https://github.com/dannyYassine/vuuri/assets/1261268/a56d2889-f241-432d-abf8-be2a09377e12">

I think are coming from this line - 
https://github.com/dannyYassine/vuuri/blob/9309d53712ed7278e0e72aa21e792854ee1c0bb3/src/Vuuri.vue#L416

**Comment by dannyYassine** [comment]
This is fixed in this [PR](https://github.com/dannyYassine/vuuri/pull/16/files) and published in version 0.4.6. Thanks!
