### ISSUE TITLE
Corruption when deleting items

### ISSUE THREAD

**Issue by oddjobz** [dannyYassine/vuuri#4]
When you delete an item from a grid and the item is "not" the first item in the grid, corruption ensues. The correct element is deleted on the screen, but then an artefact appears underneath the first element in the grid, Under the hood, while the correct element is updated on the screen, the wrong item is removed from "copiedItems". I've submitted a 2-line PR which appears to fix the issue, would be great if you could take a look.

I previously encountered a number of screen corruption issues when doing other things, specifically moving between cached router-view's, I suspect this may also fix some / all of my historical issues .. :)

- https://github.com/dannyYassine/vuuri/pull/6

**Comment by oddjobz** [comment]
Still seeing artefacts on the screen in some instances, in the PR I've added {removeElements: true} to ".remove", which seems to do the trick.

**Comment by oddjobz** [comment]
Ok, the removeElements removes the screen artefacts but there are other issues, ignore the PR I just closed, I'm looking again.

**Comment by oddjobz** [comment]
Ok, re-submitted the PR with hopefully a better understanding of the issue. Seems to fix a number of issues for me.

**Comment by dannyYassine** [comment]
fixed in https://github.com/dannyYassine/vuuri/pull/10

thanks for the suggestion!
